BVRProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="/bvr")),
    path('bvr/', include('bvr.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bvr/urls.py
from django.urls import path
from . import views

app_name = 'bvr'

urlpatterns = [
    path('', views.index, name='index'),
    path('init-db', views.init_db, name='init-db'),
    path('users', views.user_list, name='users'),
    # path('users/add', views.user_add, name='user-add-form'),
    path('users/update/<user_id>/', views.user_update, name='user-update-form'),
    path('users/change-password/<user_id>/', views.user_change_password, name='user-change-password'),

    path('sectors', views.sector_list, name='sectors'),
    path('sectors/add', views.sector_add, name='sector-add-form'),
    path('sectors/update/<sector_id>/', views.sector_update, name='sector-update-form'),

    path('remains', views.remain_list, name='remains'),
    path('remains/update/<remain_id>/', views.remain_update, name='remains-update-form'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="ru">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bvr/css/bootstrap_5/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bvr/css/select2.css' %}"/>
    <link rel="stylesheet" href="{% static 'bvr/css/fontawesome/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'bvr/css/fontawesome/css/all.css' %}">

    <script src="{% static 'bvr/js/jQuery.js' %}"></script>
    <script src="{% static 'bvr/js/select2.js' %}"></script>

    <style>
        th {
            position: sticky;
            top: 0;
            z-index: 2 !important;
        }
    </style>

    {% block own_css %}{% endblock %}
    {% block title %}{% endblock %}
</head>
<body>
<form action="{% url 'logout' %}" id="logout_form" method="post">
    {% csrf_token %}
</form>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'bvr/img/favicon.ico' %}" alt="" width="24" height="24"
                 class="d-inline-block align-text-top">
            ОАО «Белвторресурсы»
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                {% if request.user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bvr:users' %}">Пользователи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bvr:sectors' %}">Участки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bvr:remains' %}">Остатки</a>
                    </li>
                {% endif %}

                {% comment %}<li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'applicant:applicant-add-form' %}">Ввод
                        данных</a>
                </li>{% endcomment %}
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.last_name %}
                            {{ user.last_name }} {{ user.first_name }}
                        {% else %}
                            {{ user.username }}
                        {% endif %}

                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" onclick="sendLogOut()" style="cursor: pointer">Выход из системы</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}{% endblock %}
<script src="{% static 'bvr/js/bootstrap/bootstrap.js' %}"></script>
<script>
    $(document).ready(function () {
        $('.my-select2').select2();
    });

    function sendLogOut() {
        let logoutForm = document.getElementById("logout_form");
        logoutForm.submit();

    }
</script>
{% block own_js %}{% endblock %}

</body>
</html>