BVRProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="/bvr")),
    path('bvr/', include('bvr.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bvr/urls.py
from django.urls import path
from . import views

app_name = 'bvr'

urlpatterns = [
    path('', views.index, name='index'),
    path('init-db', views.init_db, name='init-db'),
    path('users', views.user_list, name='users'),
    # path('users/add', views.user_add, name='user-add-form'),
    path('users/update/<user_id>/', views.user_update, name='user-update-form'),
    path('users/change-password/<user_id>/', views.user_change_password, name='user-change-password'),

    path('sectors', views.sector_list, name='sectors'),
    path('sectors/add', views.sector_add, name='sector-add-form'),
    path('sectors/update/<sector_id>/', views.sector_update, name='sector-update-form'),

    path('remains', views.remain_list, name='remains'),
    path('remains/update/<remain_id>/', views.remain_update, name='remains-update-form'),
]

bvr/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class District(models.Model):
    district_name = models.CharField(max_length=255)

    def __str__(self):
        return self.district_name

    class Meta:
        verbose_name = 'District'
        verbose_name_plural = 'Districts'
        ordering = ("district_name",)


class ProcurementSector(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE, verbose_name="District")
    sector_number = models.IntegerField(verbose_name="Sector Number")
    sector_address = models.TextField(verbose_name="Sector address")
    comments = models.TextField(verbose_name="Comments", blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.id:
            super(ProcurementSector, self).save(*args, **kwargs)
            Remains.objects.create(sector=self)
        else:
            super(ProcurementSector, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.sector_number)

    class Meta:
        verbose_name = 'Участок заготовки'
        verbose_name_plural = 'Участки заготовки'
        ordering = ("sector_number",)


class CustomUser(AbstractUser):
    sector = models.OneToOneField(ProcurementSector, on_delete=models.CASCADE, verbose_name="Sector", blank=True,
                                  null=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ("username",)


class Remains(models.Model):
    sector = models.OneToOneField(ProcurementSector, on_delete=models.CASCADE, verbose_name="Sector", blank=True,
                                  null=True)
    wastepaper_count = models.IntegerField(verbose_name="Макулатура (количество)", blank=True, null=True)
    wastepaper_needs_exportation = models.BooleanField(verbose_name="Макулатура (нужен вывоз)", default=False)
    cullet_count = models.IntegerField(verbose_name="Стеклобой (количество)", blank=True, null=True)
    cullet_needs_exportation = models.BooleanField(verbose_name="Стеклобой (нужен вывоз)", default=False)

    polyethylene_count = models.IntegerField(verbose_name="Полиэтилен (количество)", blank=True, null=True)
    polyethylene_needs_exportation = models.BooleanField(verbose_name="Полиэтилен (нужен вывоз)", default=False)

    scrap_metal_count = models.IntegerField(verbose_name="Металлолом (количество)", blank=True, null=True)
    scrap_metal_needs_exportation = models.BooleanField(verbose_name="Металлолом (нужен вывоз)", default=False)
    date_time_updated = models.DateTimeField(verbose_name="Дата и время последнего редактирования", auto_now=True)

    def __str__(self):
        return str(self.sector.sector_number)

    class Meta:
        verbose_name = 'Остаток материальных ресурсов'
        verbose_name_plural = 'Остатки материальных ресурсов'
        ordering = ("-wastepaper_needs_exportation", "-cullet_needs_exportation", "-polyethylene_needs_exportation",
                    "-scrap_metal_needs_exportation")

bvr/forms.py
from django.forms import ModelForm
from .models import ProcurementSector, Remains, CustomUser


class ProcurementSectorForm(ModelForm):
    class Meta:
        model = ProcurementSector
        fields = '__all__'


class RemainsForm(ModelForm):
    class Meta:
        model = Remains
        fields = '__all__'


class CustomUserForm(ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'is_superuser', 'is_active', 'sector']

bvr/views.py
from django.shortcuts import render, get_object_or_404

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.paginator import Paginator

from .models import CustomUser, Remains, ProcurementSector, District
from .forms import ProcurementSectorForm, RemainsForm, CustomUserForm
from .filters import CustomUserFilter, ProcurementSectorFilter, RemainsFilter
from django.core.exceptions import PermissionDenied


@login_required
def index(request):
    if request.user.is_superuser:
        return redirect('bvr:users')
    else:
        return redirect('bvr:remains-update-form', remain_id=request.user.sector.remains.id)


def init_db(request):
    if request.method == 'POST':
        pass
    else:
        CustomUser.objects.all().delete()
        District.objects.all().delete()
        ProcurementSector.objects.all().delete()
        Remains.objects.all().delete()
        admin_user = CustomUser.objects.create_user("admin", "", "12345678")
        admin_user.is_superuser = True
        admin_user.is_staff = True
        admin_user.last_name = "Администратор"
        admin_user.save()

        import csv
        with open('1.csv') as csv_file:
            csv_reader = csv.reader(csv_file, delimiter=';')
            for row in csv_reader:
                new_district, created = District.objects.get_or_create(district_name=row[3])
                new_sector = ProcurementSector.objects.create(district=new_district, sector_number=row[1],
                                                              sector_address=row[0])
                new_user = CustomUser.objects.create_user(row[1], "", row[2])
                new_user.sector = new_sector
                new_user.last_name = row[1]
                new_user.save()

        return HttpResponse("DB init is completed!!!")


@login_required
def user_list(request):
    request.session['back_path'] = '/bvr/users?' + request.META.get('QUERY_STRING')
    qs = CustomUser.objects.all()
    if 'o' in request.GET:
        order_query = request.GET['o'].split('.')
        qs = qs.order_by(*order_query)
    f = CustomUserFilter(request.GET, queryset=qs)
    paginator = Paginator(f.qs, 50)
    page = request.GET.get('page')
    users_list = paginator.get_page(page)
    return render(request, 'bvr/users/users_list.html', {'users_list': users_list, 'filter': f})


# @login_required
# def user_add(request):
#     if request.method == 'POST':
#         form = CustomUserForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect(reverse('bvr:users'))
#         else:
#             return render(request, 'bvr/users/user_input_form.html', {'user_form': form})
#     if request.method == 'GET':
#         applicant_form = CustomUserForm()
#         return render(request, 'bvr/users/user_input_form.html', {'applicant_form': applicant_form})
#     else:
#         pass


@login_required
def user_update(request, user_id):
    if request.method == 'POST':
        obj = get_object_or_404(CustomUser, pk=user_id)
        form = CustomUserForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            back_path = request.session.get('back_path', '/')
            return HttpResponseRedirect(back_path)
        else:
            return render(request, 'bvr/users/user_update_form.html', {'user_form': form,
                                                                       'obj': obj,
                                                                       })
    else:
        obj = get_object_or_404(CustomUser, pk=user_id)
        form = CustomUserForm(instance=obj)
        return render(request, 'bvr/users/user_update_form.html', {'user_form': form,
                                                                   'obj': obj})


@login_required
def user_change_password(request, user_id):
    if request.method == 'POST':
        user = get_object_or_404(CustomUser, pk=user_id)
        new_password = request.POST['password']
        user.set_password(new_password)
        user.save()
        back_path = request.session.get('back_path', '/bvr/users')
        return HttpResponseRedirect(back_path)
    else:
        user = get_object_or_404(CustomUser, pk=user_id)
        return render(request, 'bvr/users/user_change_password_form.html', {
            'user': user})


@login_required
def sector_list(request):
    request.session['back_path'] = '/bvr/sectors?' + request.META.get('QUERY_STRING')
    qs = ProcurementSector.objects.all()
    if 'o' in request.GET:
        order_query = request.GET['o'].split('.')
        qs = qs.order_by(*order_query)
    f = ProcurementSectorFilter(request.GET, queryset=qs)
    paginator = Paginator(f.qs, 50)
    page = request.GET.get('page')
    sectors_list = paginator.get_page(page)
    return render(request, 'bvr/sectors/sectors_list.html', {'sectors_list': sectors_list, 'filter': f})


@login_required
def sector_add(request):
    if request.method == 'POST':
        form = ProcurementSectorForm(request.POST)
        if form.is_valid():
            new_sector = form.save()
            password = request.POST.get('password')
            new_user = CustomUser.objects.create_user(new_sector.sector_number, "", password)
            new_user.sector = new_sector
            new_user.last_name = new_sector.sector_number
            new_user.save()
            return HttpResponseRedirect(reverse('bvr:sectors'))
        else:
            return render(request, 'bvr/sectors/sector_input_form.html', {'sector_form': form})
    if request.method == 'GET':
        form = ProcurementSectorForm()
        return render(request, 'bvr/sectors/sector_input_form.html', {'sector_form': form})
    else:
        pass


@login_required
def sector_update(request, sector_id):
    if request.method == 'POST':
        obj = get_object_or_404(ProcurementSector, pk=sector_id)
        form = ProcurementSectorForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            back_path = request.session.get('back_path', '/')
            return HttpResponseRedirect(back_path)
        else:
            return render(request, 'bvr/sectors/sector_update_form.html', {'sector_form': form,
                                                                           'obj': obj,
                                                                           })
    else:
        obj = get_object_or_404(ProcurementSector, pk=sector_id)
        form = ProcurementSectorForm(instance=obj)
        return render(request, 'bvr/sectors/sector_update_form.html', {'sector_form': form,
                                                                       'obj': obj})


@login_required
def remain_list(request):
    if request.user.is_superuser:
        request.session['back_path'] = '/bvr/remains?' + request.META.get('QUERY_STRING')
        qs = Remains.objects.filter(sector__customuser__is_active=True)
        if 'o' in request.GET:
            order_query = request.GET['o'].split('.')
            qs = qs.order_by(*order_query)
        f = RemainsFilter(request.GET, queryset=qs)
        paginator = Paginator(f.qs, 50)
        page = request.GET.get('page')
        remains_list = paginator.get_page(page)
        return render(request, 'bvr/remains/remains_list.html', {'remains_list': remains_list, 'filter': f})
    else:
        raise PermissionDenied()


@login_required
def remain_update(request, remain_id):
    if request.method == 'POST':
        obj = get_object_or_404(Remains, pk=remain_id)
        form = RemainsForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            if request.user.is_superuser:
                back_path = request.session.get('back_path', '/')
                return HttpResponseRedirect(back_path)
            else:
                return redirect('bvr:remains-update-form', remain_id=request.user.sector.remains.id)
        else:
            return render(request, 'bvr/remains/remains_input_form.html', {'remain_form': form,
                                                                           'obj': obj,
                                                                           })
    else:
        current_user = request.user
        remains = get_object_or_404(Remains, pk=remain_id)
        form = RemainsForm(instance=remains)
        if request.user.is_superuser:
            return render(request, 'bvr/remains/remains_update_form.html', {'remain_form': form,
                                                                            'remains': remains})
        else:
            if remains.sector.customuser == current_user:
                return render(request, 'bvr/remains/remains_update_form.html', {'remain_form': form,
                                                                                'remains': remains})
            else:
                raise PermissionDenied()

bvr/templates/bvr/users/filter.html
{% load widget_tweaks %}
{% load static %}
<div class="card card-body">
    <form action="{% url 'bvr:users' %}">
        <div class="shadow p-3 mb-3 bg-body rounded">
            <div class="row">
                <div class="col-lg-6">
                    <div class="mb-3">
                        <label class="form-label">Имя пользователя (содержит)</label>
                        {% render_field filter.form.username class+="form-control" %}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="mb-3">
                        <label class="form-label">Фамилия (содержит)</label>
                        {% render_field filter.form.last_name class+="form-control" %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="mb-3">
                        <label class="form-label">Активный</label>
                        {% render_field filter.form.is_active class+="form-control" %}
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="mb-3">
                        <label class="form-label">Суперпользователь</label>
                        {% render_field filter.form.is_superuser class+="form-control" %}
                    </div>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-secondary">Поиск</button>
        <a href="{% url 'bvr:users' %}" class="btn btn-secondary">Сбросить фильтр</a>
    </form>

</div>

bvr/templates/bvr/users/user_change_password_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% load url_replace %}
{% block title %}<title>Пользователи</title>{% endblock %}
{% block content %}


    <div class="container">
        <div class="mb-4"></div>
        <h3>Смена пароля для пользователя {{ user.username }}</h3>
        <form class="needs-validation" action="{% url 'bvr:user-change-password' user_id=user.id %}" method="post"
              novalidate>{% csrf_token %}
            <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Новый пароль</label>
                <input type="password" class="form-control" id="exampleInputPassword1" name="password" required>
                <div class="invalid-feedback">Поле, обязательно для заполнения!</div>
            </div>
            <button type="submit" class="btn btn-primary">Изменить пароль</button>
        </form>
    </div>

{% endblock %}

{% block own_js %}
    <script>
        (function () {
            'use strict'
            var forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
        })()
    </script>
{% endblock %}

bvr/templates/bvr/users/user_input_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}<title>Новый пользователь</title>{% endblock %}
{% block content %}


    <div class="container">
        {% if request.user.is_superuser %}
           <form action="{% url 'bvr:user-update-form' user_id=obj.id %}" method="post"
              class="needs-validation"
              novalidate>{% csrf_token %}
        <div class="container my-3">
             {% include 'bvr/users/common/input_form.html' %}
            <div>
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </form>
        {% else %}
            У Вас недостаточно прав для просмотра этой страницы
        {% endif %}

    </div>

{% endblock %}

{% block own_js %}

{% endblock %}

bvr/templates/bvr/users/user_update_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}<title>Редактирование пользователя</title>{% endblock %}
{% block content %}
    <div class="container">
        {% if request.user.is_superuser %}

            {% if user_form.non_field_errors %}
                <div class="alert alert-danger mt-3" role="alert">
                    {% for error in user_form.non_field_errors %}
                        <b>{{ field.label }} {{ error }}</b><br>
                    {% endfor %}
                    {% for field in applicant_form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <b>{{ field.label }} {{ error }}</b><br>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}



            <form action="{% url 'bvr:user-update-form' user_id=obj.id %}" method="post"
                  class="needs-validation"
                  novalidate>{% csrf_token %}
                <div class="container my-3">
                    {% include 'bvr/users/common/input_form.html' %}
                    <div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </div>
            </form>
        {% else %}
            У Вас недостаточно прав для просмотра этой страницы
        {% endif %}

    </div>

{% endblock %}

{% block own_js %}
    <script>
        (function () {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.prototype.slice.call(forms)
                .forEach(function (form) {
                    form.addEventListener('submit', function (event) {
                        if (!form.checkValidity()) {
                            event.preventDefault()
                            event.stopPropagation()
                        }

                        form.classList.add('was-validated')
                    }, false)
                })
        })()
    </script>
{% endblock %}